Add static bridge for strings
osrf/ros2_ign pull request #1
Opened 2019-08-11 10:17 UTC by shiveshkhaitan

This adds a basic bridge for string messages.

To create the bridge
1) `ros2 run ros2_ign_bridge static_bridge`
2) Open an instance of `ign gazebo`
3) Create an ignition string msg publisher on topic `chatter`
4) `ros2 topic echo /chatter`

2019-08-14 01:02 UTC, chapulina requested changes
It's looking good!

I added some instructions to the README on bac63db. If you follow them, you'll notice that the ROS 2 -> Ignition direction is not working. I think it could be related to the namespace comment below. Could you give it a try?

2019-08-14 01:02 UTC, chapulina commented on ros2_ign_bridge/include/ros2_ign_bridge/factory.hpp
> +      ros2_node->create_publisher<ROS2_T>(topic_name, rclcpp::QoS(rclcpp::KeepLast(1)));
The value inside `rclcpp::KeepLast` is equivalent to ROS 1's `queue_size`, so we could forward `queue_size` as is done on `ros1_ign` and use it instead of hardcoding it to 1 here.

There are some notes about this on the [Dashing migration guide](https://index.ros.org//doc/ros2/Releases/Release-Dashing-Diademata/#changes-to-creating-publishers-and-subscriptions).

2019-08-14 01:02 UTC, chapulina commented on ros2_ign_bridge/src/static_bridge.cpp
> +  auto ros2_node = std::make_shared<rclcpp::Node>("test_node");
I completely get it why you called it a `test_node`. This executable feels like a demo or a test case. It's the perfect entry point for this first PR :+1:

2019-08-14 01:02 UTC, chapulina commented on ros2_ign_bridge/src/builtin_interfaces_factories.cpp
> +    (ros2_type_name == "std_msgs/String" || ros2_type_name == "") &&
The ROS 2 message types have an extra `/msg`in the middle, see [this](https://github.com/ros2/ros1_bridge/blob/b21de05ed992a7197d36222a9ce64788c1ecec48/src/static_bridge.cpp#L46) on `ros1_bridge`. There's some documentation about this subnamespace [here](https://index.ros.org/doc/ros2/Contributing/Migration-Guide/#messages-services-and-actions). Can you change all `std_msgs/String` to `std_msgs/msg/String`?

2019-08-14 10:45 UTC, shiveshkhaitan commented
>  ROS 2 -> Ignition direction is not working

Sorry I forgot to test it the other way around. Fixed in d85a6cd. I missed `rclcpp::spin` initially

2019-08-26 17:38 UTC, chapulina approved these changes
Works great!

2019-08-26 19:00 UTC, merged